import pytest

from statgpt.common.schemas.data_query_tool import DataQueryMessages
from statgpt.common.schemas.enums import InvocationSource

# (resolver method name, base field, MCP field) for every configurable message.
_MESSAGE_PAIRS = [
    ("get_no_data_for_country", "no_data_for_country", "no_data_for_country_mcp_only"),
    ("get_no_data", "no_data", "no_data_mcp_only"),
    (
        "get_data_query_executed",
        "data_query_executed_agent_only",
        "data_query_executed_mcp_only",
    ),
    ("get_multiple_datasets", "multiple_datasets_agent_only", "multiple_datasets_mcp_only"),
    ("get_invalid_time_period", "invalid_time_period", "invalid_time_period_mcp_only"),
]


@pytest.mark.parametrize("resolver,base_field,mcp_field", _MESSAGE_PAIRS)
class TestPerInvocationSourceMessages:
    """Each message has an optional MCP twin, used only on the MCP path."""

    def test_mcp_variant_used_for_mcp_only(self, resolver, base_field, mcp_field):
        messages = DataQueryMessages.model_validate({base_field: "agent", mcp_field: "mcp"})
        assert getattr(messages, resolver)(InvocationSource.MCP) == "mcp"
        assert getattr(messages, resolver)(InvocationSource.AGENT) == "agent"

    def test_falls_back_when_mcp_variant_unset(self, resolver, base_field, mcp_field):
        messages = DataQueryMessages.model_validate({base_field: "agent"})
        assert getattr(messages, resolver)(InvocationSource.MCP) == "agent"
        assert getattr(messages, resolver)(InvocationSource.AGENT) == "agent"

    def test_falls_back_when_mcp_variant_blank(self, resolver, base_field, mcp_field):
        """A blank string is treated as unset, matching the consumers' truthiness checks."""
        messages = DataQueryMessages.model_validate({base_field: "agent", mcp_field: ""})
        assert getattr(messages, resolver)(InvocationSource.MCP) == "agent"

    def test_none_when_nothing_configured(self, resolver, base_field, mcp_field):
        messages = DataQueryMessages()
        assert getattr(messages, resolver)(InvocationSource.MCP) is None
        assert getattr(messages, resolver)(InvocationSource.AGENT) is None

    def test_mcp_variant_alone_is_agent_only_none(self, resolver, base_field, mcp_field):
        """An MCP-only message must not leak into the agent flow."""
        messages = DataQueryMessages.model_validate({mcp_field: "mcp"})
        assert getattr(messages, resolver)(InvocationSource.MCP) == "mcp"
        assert getattr(messages, resolver)(InvocationSource.AGENT) is None


class TestCamelCaseAliases:
    """YAML configs use the camelCase aliases generated by BaseYamlModel."""

    def test_mcp_keys_parse_from_camel_case(self):
        messages = DataQueryMessages.model_validate(
            {
                "dataQueryExecutedAgentOnly": "agent",
                "dataQueryExecutedMcpOnly": "mcp",
                "noDataForCountryMcpOnly": "country",
                "noDataMcpOnly": "nodata",
                "multipleDatasetsMcpOnly": "datasets",
                "invalidTimePeriodMcpOnly": "period",
            }
        )
        assert messages.data_query_executed_mcp_only == "mcp"
        assert messages.no_data_for_country_mcp_only == "country"
        assert messages.no_data_mcp_only == "nodata"
        assert messages.multiple_datasets_mcp_only == "datasets"
        assert messages.invalid_time_period_mcp_only == "period"
