---
excludes:
  scopes:
    - pattern: "dev"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
    - pattern: "experiments"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for experimentation only."
resolutions:
  rule_violations:
    - message: ".*PyPI::pandas:2\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pandas-dev/pandas/blob/main/LICENSE"
    - message: ".*PyPI::numpy:1\\.26\\.4.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/numpy/numpy/blob/main/LICENSE.txt"
    - message: ".*PyPI::httpcore:1\\.0\\.9.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpcore/blob/master/LICENSE.md"
    - message: ".*PyPI::tiktoken:0\\.9\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/openai/tiktoken/blob/0.11.0/LICENSE"
    - message: ".*PyPI::urllib3:2\\.4\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/urllib3/urllib3/blob/2.5.0/LICENSE.txt"
    - message: ".*PyPI::typing-extensions:4\\.14\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Same as CPython: https://github.com/python/typing_extensions/blob/4.14.0/LICENSE"
