name: "🚀 Feature request"
description: Suggest an idea for this project
type: Feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to improve StatGPT.
        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: StatGPT Backend version
      description: Application version
      placeholder: 0.1.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
      description: |
        Describe the problem / use-case / limitation you want to address.
        Focus on **what** you need to accomplish and **why** it matters
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the proposed feature or solution?
      description: |
        Describe the feature **design or implementation** if you already have something in mind.
        PRs are welcome!
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
