import os

TOKEN_EXPIRATION_BUFFER = int(os.getenv("TOKEN_EXPIRATION_BUFFER", "120"))


class TTYDChatConfig:
    OAUTH2_TOKEN_ENDPOINT_URL = os.getenv("OAUTH2_TOKEN_ENDPOINT_URL", "")
    SCOPE = os.getenv("SERVICES_CHAT_SCOPE", "")
    CLIENT_ID = os.getenv("SERVICES_CHAT_CLIENT_ID", "")
    CLIENT_SECRET = os.getenv("SERVICES_CHAT_CLIENT_SECRET", "")


class ClientsSpaChatConfig:
    OAUTH2_TOKEN_ENDPOINT_URL = os.getenv("OAUTH2_TOKEN_ENDPOINT_URL", "")
    CLIENT_ID = os.getenv("CLIENTS_SPA_CHAT_CLIENT_ID", "")
    CLIENT_SECRET = os.getenv("CLIENTS_SPA_CHAT_CLIENT_SECRET", "")
