name: Release Workflow

on:
  push:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Test Job
  BYPASS_CHECKS: "false"
  STYLE_CHECKS_ENABLED: "true"
  STYLE_CHECKS_BYPASSED: "false"
  CODE_CHECKS_ENABLED: "true"
  CODE_CHECKS_BYPASSED: "false"
  ORT_ENABLED: "true"
  ORT_BYPASSED: "false"
  ORT_VERSION: "latest"
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "2.1.1"
  RUNS_ON: '["ubuntu-24.04"]'

  # Release Job
  CHAT_BACKEND_IMAGE: "epam/statgpt-chat-backend"
  CHAT_BACKEND_DOCKERFILE: "docker/Dockerfile.chat"
  ADMIN_BACKEND_IMAGE: "epam/statgpt-admin-backend"
  ADMIN_BACKEND_DOCKERFILE: "docker/Dockerfile.admin"
  PUSH_ENABLED: "true"
  TRIVY_ENABLED: "true"
  TRIVY_BYPASSED: "false"
  TRIVY_SEVERITY: "CRITICAL,HIGH"
  TRIVY_SEVERITY_FOR_SARIF: "CRITICAL,HIGH"
  TRIVY_LIMIT_SEVERITIES_FOR_SARIF: "true"
  MAXIMIZE_BUILD_SPACE: "false"
  PLATFORMS: "linux/amd64"
  REGISTRY: "ghcr.io"

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      bypass-checks: ${{ fromJSON(env.BYPASS_CHECKS) }}
      style-checks-enabled: ${{ fromJSON(env.STYLE_CHECKS_ENABLED) }}
      style-checks-bypassed: ${{ fromJSON(env.STYLE_CHECKS_BYPASSED) }}
      code-checks-enabled: ${{ fromJSON(env.CODE_CHECKS_ENABLED) }}
      code-checks-bypassed: ${{ fromJSON(env.CODE_CHECKS_BYPASSED) }}
      ort-enabled: ${{ fromJSON(env.ORT_ENABLED) }}
      ort-bypassed: ${{ fromJSON(env.ORT_BYPASSED) }}
      ort-version: ${{ env.ORT_VERSION }}
      python-version: ${{ env.PYTHON_VERSION }}
      poetry-version: ${{ env.POETRY_VERSION }}
      runs-on: ${{ env.RUNS_ON }}

  calculate_version:
    runs-on: ${{ fromJSON(env.RUNS_ON)[0] }}
    outputs:
      next-version: ${{ steps.semantic_versioning.outputs.next-version }}
      next-version-without-hyphens: ${{ steps.semantic_versioning.outputs.next-version-without-hyphens }}
      is-latest: ${{ steps.semantic_versioning.outputs.is-latest }}
      latest-tag: ${{ steps.semantic_versioning.outputs.latest-tag }}
    steps:
      - uses: epam/ai-dial-ci/actions/semantic_versioning@2.4.1
        id: semantic_versioning

  release:
    runs-on: ${{ fromJSON(env.RUNS_ON)[0] }}
    needs: [test, calculate_version]
    permissions:
      contents: write
      packages: write
      security-events: write
    strategy:
      matrix:
        include:
          - image-name: ${{ env.CHAT_BACKEND_IMAGE }}
            dockerfile: ${{ env.CHAT_BACKEND_DOCKERFILE }}
          - image-name: ${{ env.ADMIN_BACKEND_IMAGE }}
            dockerfile: ${{ env.ADMIN_BACKEND_DOCKERFILE }}

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@90e01b21170618765a73370fcc3abbd1684a7793 # v5
        if: ${{ fromJSON(env.MAXIMIZE_BUILD_SPACE) }}
        with:
          remove-android: "true"
          remove-dotnet: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-cached-tools: "true"
          remove-large-packages: "true"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - name: Set version in pyproject.toml for Docker build
        run: |
          sed -i "s/^version = .*/version = \"${{ needs.calculate_version.outputs.next-version-without-hyphens }}\"/g" pyproject.toml

      # Workaround: Copy the specific Dockerfile to root as "Dockerfile" (the build_docker action does not support multiple images)
      - name: Prepare Dockerfile
        run: |
          cp ${{ matrix.dockerfile }} ./Dockerfile

      - uses: epam/ai-dial-ci/actions/build_docker@2.4.1
        with:
          image-name: ${{ matrix.image-name }}
          image-tag: ${{ needs.calculate_version.outputs.next-version }}
          push-enabled: ${{ fromJSON(env.PUSH_ENABLED) }}
          trivy-enabled: ${{ fromJSON(env.TRIVY_ENABLED) }}
          bypass-checks: ${{ fromJSON(env.TRIVY_BYPASSED) }}
          trivy-severity: ${{ env.TRIVY_SEVERITY }}
          trivy-severity-for-sarif: ${{ env.TRIVY_SEVERITY_FOR_SARIF }}
          trivy-limit-severities-for-sarif: ${{ fromJSON(env.TRIVY_LIMIT_SEVERITIES_FOR_SARIF) }}
          platforms: ${{ env.PLATFORMS }}
          ghcr-username: ${{ github.actor }}
          ghcr-password: ${{ secrets.ACTIONS_BOT_TOKEN }}
          dockerhub-username: ${{ secrets.DOCKERHUB_LOGIN }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          image-extra-aliases: |
            ${{ env.REGISTRY }}/${{ matrix.image-name }}:${{ needs.calculate_version.outputs.next-version }}
            ${{ github.ref == 'refs/heads/development' && format('{0}:development', matrix.image-name) || '' }}
            ${{ github.ref == 'refs/heads/development' && format('{0}/{1}:development', env.REGISTRY, matrix.image-name) || '' }}
            ${{ startsWith(github.ref, 'refs/heads/release-') && needs.calculate_version.outputs.is-latest == 'true' && format('{0}:latest', matrix.image-name) || '' }}
            ${{ startsWith(github.ref, 'refs/heads/release-') && needs.calculate_version.outputs.is-latest == 'true' && format('{0}/{1}:latest', env.REGISTRY, matrix.image-name) || '' }}

  create_release:
    runs-on: ${{ fromJSON(env.RUNS_ON)[0] }}
    needs: [calculate_version, release]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - name: Set version in pyproject.toml for release
        run: |
          sed -i "s/^version = .*/version = \"${{ needs.calculate_version.outputs.next-version-without-hyphens }}\"/g" pyproject.toml

      - uses: epam/ai-dial-ci/actions/generate_release_notes@2.4.1
        with:
          latest-tag: ${{ needs.calculate_version.outputs.latest-tag }}

      - uses: epam/ai-dial-ci/actions/publish_tag_release@2.4.1
        with:
          tag-version: ${{ needs.calculate_version.outputs.next-version }}
          changelog-file: "/tmp/my_changelog"
          extra-commit-command: |
            git add pyproject.toml
            git commit -m '[skip ci] Update version' || true
