class ChainParametersConfig:
    """Keys to access artifacts shared between different chains/agents."""

    REQUEST = "request"
    AUTH_CONTEXT = "auth_context"
    CHOICE = "choice"
    QUERY = "query"
    TARGET_PREFILTER = "target_prefilter"
    DATA_SERVICE = "data_service"
    INDICATORS = "indicators"
    INDICATOR_ID_2_DATASET_IDS = "indicator_id_2_dataset_ids"
    DATASETS = "datasets"
    DATASETS_DICT = "datasets_dict"
    DATASET_DIMENSION_QUERIES = "dataset_dimension_queries"
    DATASET_QUERIES_FORMATTED_STR = "dataset_queries_formatted_str"
    DATASET_QUERIES = "dataset_queries"
    DATA_RESPONSES = "data_responses"
    STATE = "state"
    SUMMARIZED_DATA_QUERY = 'summarized_data_query'
    HISTORY = "history"
    TARGET = "target"
    SKIP_OUT_OF_SCOPE_CHECK = "skip_out_of_scope_check"
    OUT_OF_SCOPE = "out_of_scope"
    OUT_OF_SCOPE_REASONING = "out_of_scope_reasoning"
